# Generated by Django 4.2.2 on 2023-08-06 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accommodation", "0002_alter_hotel_sequence_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="HotelMapping",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        primary_key=True, serialize=False, verbose_name="GWG Hotel ID"
                    ),
                ),
                (
                    "hotel_name",
                    models.CharField(max_length=120, verbose_name="GWG Hotel Name"),
                ),
                ("is_charter", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="accommodation.hotel",
                        verbose_name="Master Hotel Name",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "hotel mapping",
                "db_table": "mapping_hotel",
                "ordering": ("hotel__name", "hotel_name"),
            },
        ),
        migrations.CreateModel(
            name="HotelRoomMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "room_type",
                    models.CharField(max_length=50, verbose_name="GWG Room Type"),
                ),
                (
                    "room_code",
                    models.CharField(max_length=50, verbose_name="GWG Room Code"),
                ),
                (
                    "hotel_room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="accommodation.hotelroom",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "room mapping",
                "db_table": "mapping_hotel_room",
                "unique_together": {("hotel_room", "room_type")},
            },
        ),
    ]
