# Generated by Django 4.2.2 on 2023-08-07 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0001_initial"),
        ("mapping", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OperatorMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.IntegerField(unique=True, verbose_name="GWG Operator ID"),
                ),
                (
                    "external_name",
                    models.CharField(
                        max_length=120, unique=True, verbose_name="GWG Operator Name"
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="clients.operator",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "operator mapping",
                "db_table": "mapping_operator",
            },
        ),
    ]
