# Generated by Django 4.2.2 on 2023-08-08 18:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mapping", "0002_operatormapping"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="hotelroommapping",
            options={
                "ordering": ("hotel_room__hotel__name", "hotel_room"),
                "verbose_name_plural": "room mapping",
            },
        ),
        migrations.AlterModelOptions(
            name="operatormapping",
            options={
                "ordering": ("external_name",),
                "verbose_name_plural": "operator mapping",
            },
        ),
    ]
