"""added discount field

Revision ID: 02f169e51dc8
Revises: 74c7597fcda8
Create Date: 2022-12-15 14:17:14.879568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02f169e51dc8'
down_revision = '74c7597fcda8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking_rate', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discount', sa.Float(), server_default=sa.text('0'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking_rate', schema=None) as batch_op:
        batch_op.drop_column('discount')

    # ### end Alembic commands ###
