"""renamed model

Revision ID: 26e6f8704c3a
Revises: a17b91ab8a12
Create Date: 2022-12-16 10:44:47.177841

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '26e6f8704c3a'
down_revision = 'a17b91ab8a12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking_rate', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discount_pct', sa.Float(), server_default=sa.text('0'), nullable=True))
        batch_op.drop_column('discount')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking_rate', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discount', postgresql.DOUBLE_PRECISION(precision=53), server_default=sa.text('0'), autoincrement=False, nullable=True))
        batch_op.drop_column('discount_pct')

    # ### end Alembic commands ###
