"""empty message

Revision ID: 74c7597fcda8
Revises: 
Create Date: 2022-12-12 14:16:52.027291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74c7597fcda8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operator',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('short_name', sa.String(length=10), nullable=False),
    sa.Column('category', sa.String(length=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('purchase_manager',
    sa.Column('id', sa.String(length=2), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('last_seen', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('hotel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('purchase_manager_id', sa.String(length=2), nullable=True),
    sa.ForeignKeyConstraint(['purchase_manager_id'], ['purchase_manager.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('booking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gwg_ref_id', sa.Integer(), nullable=False),
    sa.Column('gwg_res_id', sa.Integer(), nullable=False),
    sa.Column('bkg_ref', sa.String(length=50), nullable=False),
    sa.Column('operator_code', sa.String(length=10), nullable=False),
    sa.Column('guest_name', sa.String(length=100), nullable=False),
    sa.Column('import_date', sa.DateTime(), nullable=False),
    sa.Column('sales_date', sa.DateTime(), nullable=False),
    sa.Column('in_date', sa.DateTime(), nullable=False),
    sa.Column('out_date', sa.DateTime(), nullable=False),
    sa.Column('room', sa.String(length=100), nullable=False),
    sa.Column('meal', sa.String(length=24), nullable=False),
    sa.Column('days', sa.SmallInteger(), nullable=False),
    sa.Column('adult', sa.SmallInteger(), nullable=False),
    sa.Column('child', sa.SmallInteger(), nullable=False),
    sa.Column('statu4', sa.String(length=10), nullable=False),
    sa.Column('purchase', sa.Float(), nullable=False),
    sa.Column('sales', sa.Float(), nullable=False),
    sa.Column('operator_price', sa.Float(), server_default=sa.text('0'), nullable=False),
    sa.Column('gwg_purchase_id', sa.Integer(), nullable=False),
    sa.Column('gwg_purchase_name', sa.String(length=225), nullable=False),
    sa.Column('gwg_purchase_code', sa.String(length=225), nullable=False),
    sa.Column('gwg_sales_id', sa.Integer(), nullable=False),
    sa.Column('gwg_sales_name', sa.String(length=225), nullable=False),
    sa.Column('gwg_sales_code', sa.String(length=225), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=True),
    sa.Column('updated_by', sa.Integer(), server_default=sa.text('1'), nullable=True),
    sa.Column('operator_id', sa.Integer(), nullable=False),
    sa.Column('hotel_id', sa.Integer(), nullable=False),
    sa.Column('status_id', sa.Integer(), server_default=sa.text('1'), nullable=True),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotel.id'], ),
    sa.ForeignKeyConstraint(['operator_id'], ['operator.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['status.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_booking_bkg_ref'), ['bkg_ref'], unique=False)
        batch_op.create_index(batch_op.f('ix_booking_gwg_ref_id'), ['gwg_ref_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_booking_gwg_res_id'), ['gwg_res_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_booking_import_date'), ['import_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_booking_in_date'), ['in_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_booking_out_date'), ['out_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_booking_sales_date'), ['sales_date'], unique=False)

    op.create_table('hotel_mapping',
    sa.Column('hotel_id', sa.Integer(), nullable=False),
    sa.Column('gwg_hotel_id', sa.Integer(), nullable=False),
    sa.Column('gwg_hotel_name', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotel.id'], ),
    sa.PrimaryKeyConstraint('hotel_id', 'gwg_hotel_id')
    )
    op.create_table('booking_rate',
    sa.Column('reserv_id', sa.Integer(), nullable=False),
    sa.Column('e_date', sa.DateTime(), nullable=False),
    sa.Column('base_rate', sa.Float(), server_default=sa.text('0'), nullable=True),
    sa.Column('adult_supp', sa.Float(), server_default=sa.text('0'), nullable=True),
    sa.Column('child_supp', sa.Float(), server_default=sa.text('0'), nullable=True),
    sa.Column('adult_meal', sa.Float(), server_default=sa.text('0'), nullable=True),
    sa.Column('child_meal', sa.Float(), server_default=sa.text('0'), nullable=True),
    sa.Column('peak_supp', sa.Float(), server_default=sa.text('0'), nullable=True),
    sa.Column('extras', sa.Float(), server_default=sa.text('0'), nullable=True),
    sa.Column('base_rate_disc', sa.Float(), server_default=sa.text('0'), nullable=True),
    sa.Column('adult_supp_disc', sa.Float(), server_default=sa.text('0'), nullable=True),
    sa.Column('child_supp_disc', sa.Float(), server_default=sa.text('0'), nullable=True),
    sa.Column('meal_disc', sa.Float(), server_default=sa.text('0'), nullable=True),
    sa.Column('peak_supp_disc', sa.Float(), server_default=sa.text('0'), nullable=True),
    sa.Column('extras_disc', sa.Float(), server_default=sa.text('0'), nullable=True),
    sa.Column('mark_up', sa.Float(), server_default=sa.text('0'), nullable=True),
    sa.Column('gwg_purchase_id', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('gwg_purchase_code', sa.String(length=225), nullable=True),
    sa.Column('gwg_sales_id', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('gwg_sales_code', sa.String(length=225), nullable=True),
    sa.ForeignKeyConstraint(['reserv_id'], ['booking.id'], ),
    sa.PrimaryKeyConstraint('reserv_id', 'e_date')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('booking_rate')
    op.drop_table('hotel_mapping')
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_booking_sales_date'))
        batch_op.drop_index(batch_op.f('ix_booking_out_date'))
        batch_op.drop_index(batch_op.f('ix_booking_in_date'))
        batch_op.drop_index(batch_op.f('ix_booking_import_date'))
        batch_op.drop_index(batch_op.f('ix_booking_gwg_res_id'))
        batch_op.drop_index(batch_op.f('ix_booking_gwg_ref_id'))
        batch_op.drop_index(batch_op.f('ix_booking_bkg_ref'))

    op.drop_table('booking')
    op.drop_table('hotel')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    op.drop_table('status')
    op.drop_table('purchase_manager')
    op.drop_table('operator')
    # ### end Alembic commands ###
