"""separated meal discount

Revision ID: a17b91ab8a12
Revises: 02f169e51dc8
Create Date: 2022-12-15 16:37:20.668109

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a17b91ab8a12'
down_revision = '02f169e51dc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking_rate', schema=None) as batch_op:
        batch_op.add_column(sa.Column('base_rate_discount', sa.Float(), server_default=sa.text('0'), nullable=True))
        batch_op.add_column(sa.Column('adult_supp_discount', sa.Float(), server_default=sa.text('0'), nullable=True))
        batch_op.add_column(sa.Column('child_supp_discount', sa.Float(), server_default=sa.text('0'), nullable=True))
        batch_op.add_column(sa.Column('adult_meal_discount', sa.Float(), server_default=sa.text('0'), nullable=True))
        batch_op.add_column(sa.Column('child_meal_discount', sa.Float(), server_default=sa.text('0'), nullable=True))
        batch_op.add_column(sa.Column('peak_supp_discount', sa.Float(), server_default=sa.text('0'), nullable=True))
        batch_op.add_column(sa.Column('extras_discount', sa.Float(), server_default=sa.text('0'), nullable=True))
        batch_op.drop_column('peak_supp_disc')
        batch_op.drop_column('child_supp_disc')
        batch_op.drop_column('meal_disc')
        batch_op.drop_column('base_rate_disc')
        batch_op.drop_column('extras_disc')
        batch_op.drop_column('adult_supp_disc')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking_rate', schema=None) as batch_op:
        batch_op.add_column(sa.Column('adult_supp_disc', postgresql.DOUBLE_PRECISION(precision=53), server_default=sa.text('0'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('extras_disc', postgresql.DOUBLE_PRECISION(precision=53), server_default=sa.text('0'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('base_rate_disc', postgresql.DOUBLE_PRECISION(precision=53), server_default=sa.text('0'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('meal_disc', postgresql.DOUBLE_PRECISION(precision=53), server_default=sa.text('0'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('child_supp_disc', postgresql.DOUBLE_PRECISION(precision=53), server_default=sa.text('0'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('peak_supp_disc', postgresql.DOUBLE_PRECISION(precision=53), server_default=sa.text('0'), autoincrement=False, nullable=True))
        batch_op.drop_column('extras_discount')
        batch_op.drop_column('peak_supp_discount')
        batch_op.drop_column('child_meal_discount')
        batch_op.drop_column('adult_meal_discount')
        batch_op.drop_column('child_supp_discount')
        batch_op.drop_column('adult_supp_discount')
        batch_op.drop_column('base_rate_discount')

    # ### end Alembic commands ###
