# Generated by Django 4.2.2 on 2023-08-13 18:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("clients", "0002_allocationgroup_operator_allocation_group"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accommodation", "0002_alter_hotel_sequence_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoomInventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("quantity", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "basis",
                    models.CharField(
                        choices=[
                            ("freesale", "Freesale"),
                            ("allocation", "Allocation"),
                            ("on_request", "On Request"),
                        ],
                        max_length=20,
                    ),
                ),
                ("charter", models.BooleanField(db_index=True, default=False)),
                (
                    "allocation_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="clients.allocationgroup",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="accommodation.hotelroom",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "room inventory",
                "db_table": "reports_room_inventory",
                "ordering": (
                    "room__hotel__name",
                    "room__name",
                    "start_date",
                    "end_date",
                ),
            },
        ),
        migrations.CreateModel(
            name="RoomInventoryTopUp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("additional_rooms", models.PositiveIntegerField()),
                (
                    "created_by",
                    models.ForeignKey(
                        db_column="created_by",
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "room_inventory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reports.roominventory",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        db_column="updated_by",
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "room inventory",
                "db_table": "reports_room_inventory_topup",
                "ordering": ("room_inventory", "created_at"),
            },
        ),
    ]
