# Generated by Django 4.2.2 on 2023-08-06 12:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExecutionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("start_time", models.DateTimeField(default=django.utils.timezone.now)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[("success", "Success"), ("failure", "Failure")],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("note", models.TextField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "scripts_execution_log",
                "ordering": ["-start_time"],
            },
        ),
    ]
